### ISSUE TITLE
Live on the gateway?

### ISSUE THREAD

**Issue by jbenet** [rameshvarun/ipfs-share#1]
Is it accessible on the gateway? (note the gateway is readonly, but could make POSTs to your server. we can look into making the gateway writable down the road). 

Maybe would be good to have a link to the service in the readme.

:+1:

**Comment by sergeevabc** [comment]
Any news on how to upload a file to IPFS via browser and share it with the world at least for a year?

**Comment by rameshvarun** [comment]
Way back in 2015 I had this briefly accessible on the internet, but for now it is just an example of an application that one can host themselves.
